@startuml
participant Home
participant Webhook
participant Archipels
Home -> Archipels : 1 - signup link
Archipels -> Webhook: 2 - MessageReceived /signup
Webhook -> Archipels: 3 - send presentation request [emailAddress]
Archipels -> Webhook: 4 - PresentationReceived [emailAddress]
Webhook -> Archipels: 5 - send attestation offer [application + id]
@enduml
